blank_issues_enabled: false
contact_links:
  - name: 💬 General Questions and Feedback
    url: https://github.com/damianperera/TankRadar//discussions
    about: For general questions or feedback, please start a Discussion instead.
